### ISSUE TITLE
God Please help us

### ISSUE THREAD

**Issue by V0rtex420** [AntiCope/meteor-e621-integration#4] opened 2022-02-11 20:47 UTC
**Why** did you do that? 
I can offer **holy water**, if you want

**Comment by C10udburst** [comment] 2022-02-11 21:55
:trollface:

**Comment by C10udburst** [comment] 2022-02-11 21:55
yes please💦🙏

**Comment by C10udburst** [comment] 2022-02-11 21:55
also duplicate of #3

**Closed** 2022-02-12 11:16 UTC

**Comment by C10udburst** [comment] 2022-03-17 14:21
lol
